bracketSameLine: true
bracketSpacing: true
printWidth: 100
quoteProps: as-needed
semi: true
singleQuote: false
trailingComma: es5
useTabs: false
tabWidth: 2
htmlWhitespaceSensitivity: css
arrowParens: always
endOfLine: "lf"
requirePragma: false
insertPragma: false
proseWrap: preserve

# Add from Svelte
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-css-order
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
