/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Template: typeof import('../lib/autoimport')['Template']
  const Todo: typeof import('../lib/autoimport')['Todo']
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const getAllContexts: typeof import('svelte')['getAllContexts']
  const getContext: typeof import('svelte')['getContext']
  const hasContext: typeof import('svelte')['hasContext']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const setContext: typeof import('svelte')['setContext']
  const tick: typeof import('svelte')['tick']
  const z: typeof import('zod')['default']
}
